POST http://localhost:3003/api/blogs/61b77dc75c375ab198d8badc/comments
Content-type: application/json
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2l0YWFhcyIsImlkIjoiNjFiNzhhNWQyMDE1MTBjMWFiNWM3NWI1IiwiaWF0IjoxNjM5NDE4NDg5fQ.GynNTJjrYb5_A0jZw-F__QzAE6AMPMaYyjUDfHwUK-M

{
    "comment": "Speden Spelit loppu"
}